- hosts: all
  tasks:
  
    - name: "TEMPLATE modify /etc/motd"
      template:
        src: motd-generic.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644  

    - name: "SERVICE disable and stop unwanted services"
      service: 
        name="{{ item.name }}"
        state=stopped
        enabled=no
      with_items:
        - {name: 'rhsmcertd'}

    - name: "CMD disable yum plugins for subscription-manager"
      shell: 
        cmd: |          
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf
          sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/product-id.conf
                    
    - name: "USER create and/or reset users"
      user: name="{{ item.name }}" password="{{ item.password }}"
      with_items:
        - {name: 'root', password: '$6$1234$Zryf2/RyS6HKrp0nkN/Nk3u2V4AJ5H1qLVGkOMCq/EtoPV1Zu8oLlmnZkfSAiuFFGuV1zQhOY9khczRExEh/4/'}
        - {name: 'student', password: '$6$1234$Zryf2/RyS6HKrp0nkN/Nk3u2V4AJ5H1qLVGkOMCq/EtoPV1Zu8oLlmnZkfSAiuFFGuV1zQhOY9khczRExEh/4/'}

    - name: "Sudo Configuration"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0600
      with_items:
        - {src: 'sudoers.j2', dest: '/etc/sudoers.d/rhel8-workshop'}


- import_playbook: rhel8-setup-wayland.yml
- import_playbook: rhel8-setup-appstreams.yml
- import_playbook: rhel8-setup-systemd.yml
- import_playbook: rhel8-setup-firewalld.yml
- import_playbook: rhel8-setup-nftables.yml
- import_playbook: rhel8-setup-ebpf.yml
- import_playbook: rhel8-setup-boom.yml
- import_playbook: rhel8-setup-webconsole.yml
- import_playbook: rhel8-setup-podman.yml
- import_playbook: rhel8-setup-buildah.yml
- import_playbook: rhel8-setup-stratis.yml
- import_playbook: rhel8-setup-tlog.yml
