---
- hosts: localhost
  tasks:
  
    - name: "SETUP BOOM: yum install packages"
      yum: name=boom-boot state=installed
      
    - name: "SETUP BOOM: cheat file installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-checkhost.j2', dest: '/usr/local/bin/cheat-boom-checkhost.sh'} 
        - {src: 'cheat-boom-snapshot.j2', dest: '/usr/local/bin/cheat-boom-snapshot.sh'} 
        - {src: 'cheat-boom-mkgrub.j2', dest: '/usr/local/bin/cheat-boom-mkgrub.sh'} 
        - {src: 'cheat-boom-mkprofile.j2', dest: '/usr/local/bin/cheat-boom-mkprofile.sh'} 
        - {src: 'cheat-boom-lvreport.j2', dest: '/usr/local/bin/cheat-boom-lvreport.sh'} 
        - {src: 'cheat-boom-addstorage.j2', dest: '/usr/local/bin/cheat-boom-addstorage.sh'} 
        - {src: 'cheat-boom-importantstuff.j2', dest: '/usr/local/bin/cheat-boom-importantstuff.sh'} 
        - {src: 'cheat-boom-grublist.j2', dest: '/usr/local/bin/cheat-boom-grublist.sh'} 
        
