---
- hosts: localhost
  tasks:
  
    - name: "SETUP FIREWALLD: yum install firewalld"
      yum: name=firewalld state=installed

    - name: "SETUP FIREWALLD: service stop nftables"
      service: name=nftables state=stopped enabled=no

    - name: "SETUP FIREWALLD: service start firewalld"
      service: name=firewalld state=started enabled=yes
      
    - name: "SETUP FIREWALLD: cheat script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-checkhost.j2',               dest: '/usr/local/bin/cheat-firewalld-checkhost.sh'}
        - {src: 'cheat-firewalld-customconfigs.j2', dest: '/usr/local/bin/cheat-firewalld-customconfigs.sh'}

